### PR TITLE
Update meterpreter.sl

### PR DESCRIPTION
**Pull request by netniV**
Fix issue with Auxiliary scanner output

### CODE REVIEW

**Comment by gsanchez2892** [comment]
Where is this file ?

**Comment by netniV** [comment]
In the scripts folder of the source.  On a system with Armitage installed, it will be contained / compiled in the .JAR file.

**Comment by gsanchez2892** [comment]
sorry i do not understand .. i have kali 2.0 with armitage installed, what should i do to fix the error

**Comment by krapgras** [comment]
Not sure if this will be accepted there hasn't been any activity from the owner since 2016 as far as i know. But yes this is a long lasting issue that has changed a few times already.

**Comment by krapgras** [comment]
@netniV you should just link to your forked repo as i don't think this will be updated. Some other fixes/nice updates are already in the pull requests from 2015 XD

**Comment by LiquidSnowSurfer** [comment]
Confirmed the fix works. Tested in Kali 2017.3

Thanks!

**Comment by gsanchez2892** [comment]
@LiquidSnowSurfer can you comment where is a folder that need modify?

**Comment by netniV** [comment]
@LiquidSnowSurfer Thanks for confirming it :)

@gsanchez2892 You need to download the source and compile it.  You can use my repository which already has this fix in it and is otherwise no different to this repo at the moment.

**Comment by LiquidSnowSurfer** [comment]
@gsanchez2892

It's in /usr/share/armitage
Rename armitage.jar to .zip then open it (no need to extract) 
Within the zip you should find scripts/meterpreter.sl
Update line 381, save and rename the zip back to .jar.

**Comment by gsanchez2892** [comment]
thanks so much. Confirmed the fix works.

**Comment by Ezeqielle** [comment]
hello i have use the patch but now the scan RHOSTS don't work it don't start some one can help me please ?

**Comment by h00die-gr3y** [comment]
Thanks Guys, works like a charm !

**Comment by netniV** [comment]
Closing due to lack of response from repo owner.  Patch will remain on my repo.

**Pull request closed without merging**
